DEBUG 2023-09-06 20:42:33.419 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-06 20:42:33.419 UTC: 	 Running on: Linux cmslpc154.fnal.gov 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 08:37:40 CST 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2023-09-06 20:42:33.419 UTC: 	 Executing command: 'submit'
DEBUG 2023-09-06 20:42:33.420 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2023-09-06 20:42:33.421 UTC: 	 Will use CRAB configuration file crab_clusteringAnalyzer_QCDMC2000toInf_2018_TEST_cfg.py
DEBUG 2023-09-06 20:42:33.422 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-09-06 20:42:33.429 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-09-06 20:42:33.430 UTC: 	 Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_000' already exists 
Please change the requestName in the config file
ERROR 2023-09-06 20:42:33.430 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_000' already exists 
Please change the requestName in the config file
INFO 2023-09-06 20:42:33.433 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab.log
DEBUG 2023-09-07 21:06:52.396 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-07 21:06:52.396 UTC: 	 Running on: Linux cmslpc172.fnal.gov 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 08:37:40 CST 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2023-09-07 21:06:52.396 UTC: 	 Executing command: 'status'
DEBUG 2023-09-07 21:06:52.397 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2023-09-07 21:06:52.399 UTC: 	 Error: crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVarsAndNEWBtagSF_JECEvaluator_000 is not a valid CRAB project directory.
ERROR 2023-09-07 21:06:52.399 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVarsAndNEWBtagSF_JECEvaluator_000 is not a valid CRAB project directory.
INFO 2023-09-07 21:06:52.401 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab.log
DEBUG 2023-09-07 22:32:44.353 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-07 22:32:44.353 UTC: 	 Running on: Linux cmslpc172.fnal.gov 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 08:37:40 CST 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2023-09-07 22:32:44.353 UTC: 	 Executing command: 'status'
DEBUG 2023-09-07 22:32:44.354 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2023-09-07 22:32:44.366 UTC: 	 Error: crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVars_allJERs_000scram is not a valid CRAB project directory.
ERROR 2023-09-07 22:32:44.366 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVars_allJERs_000scram is not a valid CRAB project directory.
INFO 2023-09-07 22:32:44.369 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab.log
DEBUG 2023-09-11 22:41:14.029 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-11 22:41:14.029 UTC: 	 Running on: Linux cmslpc116.fnal.gov 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 08:37:40 CST 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2023-09-11 22:41:14.029 UTC: 	 Executing command: 'submit'
DEBUG 2023-09-11 22:41:14.030 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2023-09-11 22:41:14.032 UTC: 	 Will use CRAB configuration file crab_clusteringAnalyzer_QCDMC2000toInf_2018_TEST_cfg.py
DEBUG 2023-09-11 22:41:14.032 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-09-11 22:41:14.054 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-09-11 22:41:14.056 UTC: 	 Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVars_wTxtJetEvaluator__000' already exists 
Please change the requestName in the config file
ERROR 2023-09-11 22:41:14.056 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab_projects/crab_clustAlg_QCDMC2000toInf_2018_TEST_fillSJVars_wTxtJetEvaluator__000' already exists 
Please change the requestName in the config file
INFO 2023-09-11 22:41:14.059 UTC: 	 Log file is /uscms_data/d3/cannaert/analysis/CMSSW_10_6_30/src/crab.log
DEBUG 2023-09-11 23:58:43.085 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-11 23:58:43.085 UTC: 	 Running on: Linux cmslpc178.fnal.gov 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 08:37:40 CST 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2023-09-11 23:58:43.085 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-09-11 23:58:43.085 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
